# Generated by Django 3.2.4 on 2021-06-16 16:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('table_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=50, verbose_name='Hash идентификатора wi-fi клиента')),
            ],
        ),
        migrations.CreateModel(
            name='FlatsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flats', models.IntegerField(verbose_name='Количество квартир')),
                ('address', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('optim_config', models.BooleanField(default=False)),
                ('generalizing_oper', models.CharField(choices=[('sum', 'Sum'), ('ave', 'Average')], default='ave', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OfficesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена аренды')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('address', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на объявление')),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='RentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена аренды')),
                ('address', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=50, null=True, verbose_name='Hash идентификатора пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='WAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20, verbose_name='ID точки доступа')),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='СosmeticsStoreLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupermarketLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.activity', verbose_name='Вид деятельности')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseChemicLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistryLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoordinateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
                ('processed_value', models.FloatField()),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время подключения к wi-fi')),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.wap', verbose_name='Точка доступа')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.device', verbose_name='Устройство')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeautySaloonLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarbershopLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.scope'),
        ),
    ]
