# Generated by Django 3.2.4 on 2021-06-09 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.CharField(max_length=10, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=10, verbose_name='Широта')),
                ('raw_values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None, verbose_name='Необработанные значения')),
                ('processed_value', models.FloatField()),
            ],
        ),
    ]
