# Generated by Django 3.2.4 on 2021-06-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_coordinatedata_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerylayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='barbershoplayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='barlayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='beautysaloonlayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='cafelayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='cliniclayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='dentistrylayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='housechemiclayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='layer',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='supermarketlayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='сosmeticsstorelayers',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
    ]
