# Generated by Django 3.2.4 on 2021-06-12 07:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210609_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.CharField(max_length=10, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=10, verbose_name='Широта')),
                ('distance', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('optim_config', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20, verbose_name='ID точки доступа')),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
        migrations.AlterField(
            model_name='coordinatedata',
            name='lat',
            field=models.CharField(max_length=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinatedata',
            name='lon',
            field=models.CharField(max_length=20, verbose_name='Долгота'),
        ),
        migrations.CreateModel(
            name='BarbershopLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='BarLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='CafeLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='ClinicLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='DentistryLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='HouseChemicLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='СosmeticsStoreLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='OrganizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.activity', verbose_name='Вид деятельности')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric'),
        ),
        migrations.AddField(
            model_name='activity',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.scope'),
        ),
    ]
