# Generated by Django 3.2.4 on 2021-06-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210612_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=50, verbose_name='Hash идентификатора wi-fi клиента')),
            ],
        ),
        migrations.CreateModel(
            name='RentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена аренды')),
                ('address', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=50, null=True, verbose_name='Hash идентификатора пользователя')),
            ],
        ),
        migrations.AddField(
            model_name='coordinatedata',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.metric'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время подключения к wi-fi')),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.wap', verbose_name='Точка доступа')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.device', verbose_name='Устройство')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.user', verbose_name='Пользователь')),
            ],
        ),
    ]
