# Generated by Django 3.2.4 on 2021-06-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210612_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flats', models.IntegerField(verbose_name='Количество квартир')),
                ('address', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
        migrations.RemoveField(
            model_name='layer',
            name='distance',
        ),
        migrations.AddField(
            model_name='barbershoplayers',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='barlayers',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='cafelayers',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='cliniclayers',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='dentistrylayers',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='housechemiclayers',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AddField(
            model_name='layer',
            name='lat_distance',
            field=models.FloatField(default=0.0035),
        ),
        migrations.AddField(
            model_name='layer',
            name='lon_distance',
            field=models.FloatField(default=0.007),
        ),
        migrations.AddField(
            model_name='metric',
            name='generalizing_oper',
            field=models.CharField(choices=[('sum', 'Sum'), ('ave', 'Average')], default='ave', max_length=3),
        ),
        migrations.AddField(
            model_name='сosmeticsstorelayers',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='lon',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
