# Generated by Django 3.2.4 on 2021-06-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210613_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена аренды')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('address', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на объявление')),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
    ]
