# Generated by Django 3.2.4 on 2021-06-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_officesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.CharField(max_length=20, verbose_name='Долгота')),
                ('lat', models.CharField(max_length=20, verbose_name='Широта')),
            ],
        ),
    ]
