# Generated by Django 3.2.4 on 2021-06-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20210613_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='table_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='barbershoplayers',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AlterField(
            model_name='barlayers',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AlterField(
            model_name='cafelayers',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AlterField(
            model_name='housechemiclayers',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.AlterField(
            model_name='сosmeticsstorelayers',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity'),
        ),
        migrations.CreateModel(
            name='SupermarketLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
                ('activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='BeautySaloonLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
                ('activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity')),
            ],
            bases=('db.layer',),
        ),
        migrations.CreateModel(
            name='BakeryLayers',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.layer')),
                ('activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.activity')),
            ],
            bases=('db.layer',),
        ),
    ]
