# Generated by Django 3.2.4 on 2021-06-14 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20210614_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='СosmeticsStoreLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupermarketLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseChemicLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentistryLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeautySaloonLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarbershopLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon_distance', models.FloatField(default=0.007)),
                ('lat_distance', models.FloatField(default=0.0035)),
                ('value', models.FloatField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
